import os
import re

def write_names(image_dir, write_dir):
    breed_names = os.listdir(image_dir)
    breed_names.sort()
    cleaned = [clean_names(name) for name in breed_names]
    with open(os.path.join(write_dir, 'breeds.txt'), 'w') as f:
        for name in cleaned:
            f.write(f"{name}\n")

def clean_names(name):
    name=re.sub('^n[0-9]+-', '', name)
    name=name.split("_")
    name=" ".join([word.capitalize() for word in name])
    return name

DOG_BREEDS=[
    "Chihuahua",
    "Japanese Spaniel",
    "Maltese Dog",
    "Pekinese",
    "Shih-tzu",
    "Blenheim Spaniel",
    "Papillon",
    "Toy Terrier",
    "Rhodesian Ridgeback",
    "Afghan Hound",
    "Basset",
    "Beagle",
    "Bloodhound",
    "Bluetick",
    "Black-and-tan Coonhound",
    "Walker Hound",
    "English Foxhound",
    "Redbone",
    "Borzoi",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Whippet",
    "Ibizan Hound",
    "Norwegian Elkhound",
    "Otterhound",
    "Saluki",
    "Scottish Deerhound",
    "Weimaraner",
    "Staffordshire Bullterrier",
    "American Staffordshire Terrier",
    "Bedlington Terrier",
    "Border Terrier",
    "Kerry Blue Terrier",
    "Irish Terrier",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Yorkshire Terrier",
    "Wire-haired Fox Terrier",
    "Lakeland Terrier",
    "Sealyham Terrier",
    "Airedale",
    "Cairn",
    "Australian Terrier",
    "Dandie Dinmont",
    "Boston Bull",
    "Miniature Schnauzer",
    "Giant Schnauzer",
    "Standard Schnauzer",
    "Scotch Terrier",
    "Tibetan Terrier",
    "Silky Terrier",
    "Soft-coated Wheaten Terrier",
    "West Highland White Terrier",
    "Lhasa",
    "Flat-coated Retriever",
    "Curly-coated Retriever",
    "Golden Retriever",
    "Labrador Retriever",
    "Chesapeake Bay Retriever",
    "German Short-haired Pointer",
    "Vizsla",
    "English Setter",
    "Irish Setter",
    "Gordon Setter",
    "Brittany Spaniel",
    "Clumber",
    "English Springer",
    "Welsh Springer Spaniel",
    "Cocker Spaniel",
    "Sussex Spaniel",
    "Irish Water Spaniel",
    "Kuvasz",
    "Schipperke",
    "Groenendael",
    "Malinois",
    "Briard",
    "Kelpie",
    "Komondor",
    "Old English Sheepdog",
    "Shetland Sheepdog",
    "Collie",
    "Border Collie",
    "Bouvier Des Flandres",
    "Rottweiler",
    "German Shepherd",
    "Doberman",
    "Miniature Pinscher",
    "Greater Swiss Mountain Dog",
    "Bernese Mountain Dog",
    "Appenzeller",
    "Entlebucher",
    "Boxer",
    "Bull Mastiff",
    "Tibetan Mastiff",
    "French Bulldog",
    "Great Dane",
    "Saint Bernard",
    "Eskimo Dog",
    "Malamute",
    "Siberian Husky",
    "Affenpinscher",
    "Basenji",
    "Pug",
    "Leonberg",
    "Newfoundland",
    "Great Pyrenees",
    "Samoyed",
    "Pomeranian",
    "Chow",
    "Keeshond",
    "Brabancon Griffon",
    "Pembroke",
    "Cardigan",
    "Toy Poodle",
    "Miniature Poodle",
    "Standard Poodle",
    "Mexican Hairless",
    "Dingo",
    "Dhole",
    "African Hunting Dog",
]


TSINGHUA_DOG_BREEDS=['Shiba',
 'French Bulldog',
 'Siberian Husky',
 'Malamute',
 'Pomeranian',
 'Airedale',
 'Miniature Poodle',
 'Affenpinscher',
 'Schipperke',
 'Australian Terrier',
 'Welsh Springer Spaniel',
 'Curly Coated Retriever',
 'Staffordshire Bullterrier',
 'Norwich Terrier',
 'Tibetan Terrier',
 'English Setter',
 'Norfolk Terrier',
 'Pembroke',
 'Tibetan Mastiff',
 'Border Terrier',
 'Great Dane',
 'Scotch Terrier',
 'Flat Coated Retriever',
 'Saluki',
 'Irish Setter',
 'Blenheim Spaniel',
 'Irish Terrier',
 'Bloodhound',
 'Redbone',
 'West Highland White Terrier',
 'Brabancon Griffon',
 'Dhole',
 'Kelpie',
 'Doberman',
 'Ibizan Hound',
 'Vizsla',
 'Cairn',
 'German Shepherd',
 'African Hunting Dog',
 'Dandie Dinmont',
 'Sealyham Terrier',
 'German Short Haired Pointer',
 'Bernese Mountain Dog',
 'Saint Bernard',
 'Leonberg',
 'Bedlington Terrier',
 'Newfoundland',
 'Lhasa',
 'Chesapeake Bay Retriever',
 'Lakeland Terrier',
 'Walker Hound',
 'American Staffordshire Terrier',
 'Otterhound',
 'Sussex Spaniel',
 'Norwegian Elkhound',
 'Bluetick',
 'Dingo',
 'Irish Water Spaniel',
 'Samoyed',
 'Fila Braziliero',
 'Standard Schnauzer',
 'Mexican Hairless',
 'Entlebucher',
 'Afghan Hound',
 'Kuvasz',
 'English Foxhound',
 'Keeshond',
 'Irish Wolfhound',
 'Scottish Deerhound',
 'Rottweiler',
 'Black And Tan Coonhound',
 'Great Pyrenees',
 'Boxer',
 'Wire Haired Fox Terrier',
 'Borzoi',
 'Groenendael',
 'Collie',
 'Gordon Setter',
 'Kerry Blue Terrier',
 'Briard',
 'Rhodesian Ridgeback',
 'Boston Bull',
 'Bull Mastiff',
 'Silky Terrier',
 'Brittany Spaniel',
 'Eskimo Dog',
 'Giant Schnauzer',
 'Malinois',
 'Bouvier Des Flandres',
 'Whippet',
 'Appenzeller',
 'Chinese Crested Dog',
 'Miniature Schnauzer',
 'Soft Coated Wheaten Terrier',
 'Weimaraner',
 'Clumber',
 'Greater Swiss Mountain Dog',
 'Toy Terrier',
 'Italian Greyhound',
 'Basset',
 'Basenji',
 'Australian Shepherd',
 'Maltese Dog',
 'Japanese Spaniel',
 'Cane Carso',
 'Japanese Spitzes',
 'Old English Sheepdog',
 'Black Sable',
 'Border Collie',
 'Shetland Sheepdog',
 'English Springer',
 'Beagle',
 'Cocker Spaniel',
 'Cardigan',
 'Toy Poodle',
 'Bichon Frise',
 'Standard Poodle',
 'Komondor',
 'Chow',
 'Chinese Rural Dog',
 'Yorkshire Terrier',
 'Labrador Retriever',
 'Shih Tzu',
 'Chihuahua',
 'Pekinese',
 'Golden Retriever',
 'Miniature Pinscher',
 'Teddy',
 'Pug',
 'Papillon']
