import os

def write_names(image_dir, write_dir):
    breed_names = os.listdir(image_dir)
    breed_names.sort()
    cleaned = [clean_names(name) for name in breed_names]
    with open(os.path.join(write_dir, 'breeds.txt'), 'w') as f:
        for name in cleaned:
            f.write(f"{name}\n")

def clean_names(name):
    name=name.split('-')[1]
    name=name.split("_")
    name=" ".join([word.capitalize() for word in name])
    return name

DOG_BREEDS=[
    "Chihuahua",
    "Japanese Spaniel",
    "Maltese Dog",
    "Pekinese",
    "Shih",
    "Blenheim Spaniel",
    "Papillon",
    "Toy Terrier",
    "Rhodesian Ridgeback",
    "Afghan Hound",
    "Basset",
    "Beagle",
    "Bloodhound",
    "Bluetick",
    "Black",
    "Walker Hound",
    "English Foxhound",
    "Redbone",
    "Borzoi",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Whippet",
    "Ibizan Hound",
    "Norwegian Elkhound",
    "Otterhound",
    "Saluki",
    "Scottish Deerhound",
    "Weimaraner",
    "Staffordshire Bullterrier",
    "American Staffordshire Terrier",
    "Bedlington Terrier",
    "Border Terrier",
    "Kerry Blue Terrier",
    "Irish Terrier",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Yorkshire Terrier",
    "Wire",
    "Lakeland Terrier",
    "Sealyham Terrier",
    "Airedale",
    "Cairn",
    "Australian Terrier",
    "Dandie Dinmont",
    "Boston Bull",
    "Miniature Schnauzer",
    "Giant Schnauzer",
    "Standard Schnauzer",
    "Scotch Terrier",
    "Tibetan Terrier",
    "Silky Terrier",
    "Soft",
    "West Highland White Terrier",
    "Lhasa",
    "Flat",
    "Curly",
    "Golden Retriever",
    "Labrador Retriever",
    "Chesapeake Bay Retriever",
    "German Short",
    "Vizsla",
    "English Setter",
    "Irish Setter",
    "Gordon Setter",
    "Brittany Spaniel",
    "Clumber",
    "English Springer",
    "Welsh Springer Spaniel",
    "Cocker Spaniel",
    "Sussex Spaniel",
    "Irish Water Spaniel",
    "Kuvasz",
    "Schipperke",
    "Groenendael",
    "Malinois",
    "Briard",
    "Kelpie",
    "Komondor",
    "Old English Sheepdog",
    "Shetland Sheepdog",
    "Collie",
    "Border Collie",
    "Bouvier Des Flandres",
    "Rottweiler",
    "German Shepherd",
    "Doberman",
    "Miniature Pinscher",
    "Greater Swiss Mountain Dog",
    "Bernese Mountain Dog",
    "Appenzeller",
    "Entlebucher",
    "Boxer",
    "Bull Mastiff",
    "Tibetan Mastiff",
    "French Bulldog",
    "Great Dane",
    "Saint Bernard",
    "Eskimo Dog",
    "Malamute",
    "Siberian Husky",
    "Affenpinscher",
    "Basenji",
    "Pug",
    "Leonberg",
    "Newfoundland",
    "Great Pyrenees",
    "Samoyed",
    "Pomeranian",
    "Chow",
    "Keeshond",
    "Brabancon Griffon",
    "Pembroke",
    "Cardigan",
    "Toy Poodle",
    "Miniature Poodle",
    "Standard Poodle",
    "Mexican Hairless",
    "Dingo",
    "Dhole",
    "African Hunting Dog",
]
