import os
import re

def write_names(image_dir, write_dir):
    breed_names = os.listdir(image_dir)
    breed_names.sort()
    cleaned = [clean_names(name) for name in breed_names]
    with open(os.path.join(write_dir, 'breeds.txt'), 'w') as f:
        for name in cleaned:
            f.write(f"{name}\n")

def clean_names(name):
    name=re.sub('^n[0-9]+-', '', name)
    name=name.split("_")
    name=" ".join([word.capitalize() for word in name])
    return name

DOG_BREEDS=[
    "Chihuahua",
    "Japanese Spaniel",
    "Maltese Dog",
    "Pekinese",
    "Shih-tzu",
    "Blenheim Spaniel",
    "Papillon",
    "Toy Terrier",
    "Rhodesian Ridgeback",
    "Afghan Hound",
    "Basset",
    "Beagle",
    "Bloodhound",
    "Bluetick",
    "Black-and-tan Coonhound",
    "Walker Hound",
    "English Foxhound",
    "Redbone",
    "Borzoi",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Whippet",
    "Ibizan Hound",
    "Norwegian Elkhound",
    "Otterhound",
    "Saluki",
    "Scottish Deerhound",
    "Weimaraner",
    "Staffordshire Bullterrier",
    "American Staffordshire Terrier",
    "Bedlington Terrier",
    "Border Terrier",
    "Kerry Blue Terrier",
    "Irish Terrier",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Yorkshire Terrier",
    "Wire-haired Fox Terrier",
    "Lakeland Terrier",
    "Sealyham Terrier",
    "Airedale",
    "Cairn",
    "Australian Terrier",
    "Dandie Dinmont",
    "Boston Bull",
    "Miniature Schnauzer",
    "Giant Schnauzer",
    "Standard Schnauzer",
    "Scotch Terrier",
    "Tibetan Terrier",
    "Silky Terrier",
    "Soft-coated Wheaten Terrier",
    "West Highland White Terrier",
    "Lhasa",
    "Flat-coated Retriever",
    "Curly-coated Retriever",
    "Golden Retriever",
    "Labrador Retriever",
    "Chesapeake Bay Retriever",
    "German Short-haired Pointer",
    "Vizsla",
    "English Setter",
    "Irish Setter",
    "Gordon Setter",
    "Brittany Spaniel",
    "Clumber",
    "English Springer",
    "Welsh Springer Spaniel",
    "Cocker Spaniel",
    "Sussex Spaniel",
    "Irish Water Spaniel",
    "Kuvasz",
    "Schipperke",
    "Groenendael",
    "Malinois",
    "Briard",
    "Kelpie",
    "Komondor",
    "Old English Sheepdog",
    "Shetland Sheepdog",
    "Collie",
    "Border Collie",
    "Bouvier Des Flandres",
    "Rottweiler",
    "German Shepherd",
    "Doberman",
    "Miniature Pinscher",
    "Greater Swiss Mountain Dog",
    "Bernese Mountain Dog",
    "Appenzeller",
    "Entlebucher",
    "Boxer",
    "Bull Mastiff",
    "Tibetan Mastiff",
    "French Bulldog",
    "Great Dane",
    "Saint Bernard",
    "Eskimo Dog",
    "Malamute",
    "Siberian Husky",
    "Affenpinscher",
    "Basenji",
    "Pug",
    "Leonberg",
    "Newfoundland",
    "Great Pyrenees",
    "Samoyed",
    "Pomeranian",
    "Chow",
    "Keeshond",
    "Brabancon Griffon",
    "Pembroke",
    "Cardigan",
    "Toy Poodle",
    "Miniature Poodle",
    "Standard Poodle",
    "Mexican Hairless",
    "Dingo",
    "Dhole",
    "African Hunting Dog",
]


TSINGHUA_DOG_BREEDS=['Affenpinscher',
 'Afghan Hound',
 'African Hunting Dog',
 'Airedale',
 'American Staffordshire Terrier',
 'Appenzeller',
 'Australian Shepherd',
 'Australian Terrier',
 'Basenji',
 'Basset',
 'Beagle',
 'Bedlington Terrier',
 'Bernese Mountain Dog',
 'Bichon Frise',
 'Black-and-tan Coonhound',
 'Black Sable',
 'Blenheim Spaniel',
 'Bloodhound',
 'Bluetick',
 'Border Collie',
 'Border Terrier',
 'Borzoi',
 'Boston Bull',
 'Bouvier Des Flandres',
 'Boxer',
 'Brabancon Griffon',
 'Briard',
 'Brittany Spaniel',
 'Bull Mastiff',
 'Cairn',
 'Cane Carso',
 'Cardigan',
 'Chesapeake Bay Retriever',
 'Chihuahua',
 'Chinese Crested Dog',
 'Chow',
 'Clumber',
 'Cocker Spaniel',
 'Collie',
 'Curly-coated Retriever',
 'Dandie Dinmont',
 'Dhole',
 'Dingo',
 'Doberman',
 'English Foxhound',
 'English Setter',
 'English Springer',
 'Entlebucher',
 'Eskimo Dog',
 'Fila braziliero',
 'Flat-coated Retriever',
 'French Bulldog',
 'German Shepherd',
 'German Short-haired Pointer',
 'Giant Schnauzer',
 'Golden Retriever',
 'Gordon Setter',
 'Great Dane',
 'Great Pyrenees',
 'Greater Swiss Mountain Dog',
 'Groenendael',
 'Ibizan Hound',
 'Irish Setter',
 'Irish Terrier',
 'Irish Water Spaniel',
 'Irish Wolfhound',
 'Italian Greyhound',
 'Japanese Spaniel',
 'Japanese Spitzes',
 'Keeshond',
 'Kelpie',
 'Kerry Blue Terrier',
 'Komondor',
 'Kuvasz',
 'Labrador Retriever',
 'Lakeland Terrier',
 'Leonberg',
 'Lhasa',
 'Malamute',
 'Malinois',
 'Maltese Dog',
 'Mexican Hairless',
 'Miniature Pinscher',
 'Miniature Poodle',
 'Miniature Schnauzer',
 'Newfoundland',
 'Norfolk Terrier',
 'Norwegian Elkhound',
 'Norwich Terrier',
 'Old English Sheepdog',
 'Otterhound',
 'Papillon',
 'Pekinese',
 'Pembroke',
 'Pomeranian',
 'Pug',
 'Redbone',
 'Rhodesian Ridgeback',
 'Rottweiler',
 'Saint Bernard',
 'Saluki',
 'Samoyed',
 'Schipperke',
 'Scotch Terrier',
 'Scottish Deerhound',
 'Sealyham Terrier',
 'Shetland Sheepdog',
 'Shiba',
 'Shih-Tzu',
 'Siberian Husky',
 'Silky Terrier',
 'Soft-coated Wheaten Terrier',
 'Staffordshire Bullterrier',
 'Standard Poodle',
 'Standard Schnauzer',
 'Sussex Spaniel',
 'Tibetan Mastiff',
 'Tibetan Terrier',
 'Toy Poodle',
 'Toy Terrier',
 'Vizsla',
 'Walker Hound',
 'Weimaraner',
 'Welsh Springer Spaniel',
 'West Highland White Terrier',
 'Whippet',
 'Wire-haired Fox Terrier',
 'Yorkshire Terrier']
